# Generated by Django 3.2.9 on 2021-12-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productvariant_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productvariant',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
