# Generated by Django 3.2.9 on 2021-12-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productvariant_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productvariant',
            managers=[
            ],
        ),
    ]
